/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_AUDIO_FILES           2
#define MMAP_AUDIO_CHECKSUM        0x77DA

enum MMAP_AUDIO_LISTS {
    MMAP_AUDIO_DUKOU_WAV = 0,        /*!< dukou.wav */
    MMAP_AUDIO_HOTEL_CALIFORNIA_WAV = 1,        /*!< hotel_california.wav */
};
