/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_GIF_FILES           1
#define MMAP_GIF_CHECKSUM        0xF45A

enum MMAP_GIF_LISTS {
    MMAP_GIF_FRAME_000_SQOI = 0,        /*!< frame_000.sqoi */
};
